apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: default-model-config
  namespace: kagent
spec:
  apiKeySecret: kagent-agentgateway
  apiKeySecretKey: OPENAI_API_KEY
  provider: OpenAI
  model: gemini-2.5-flash
  openAI:
    baseUrl: http://agentgateway-proxy.agentgateway-system.svc.cluster.local/v1beta/openai
