apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentregistry.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentregistry.labels" . | nindent 4 }}
