apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-api-crds.yaml
  - agentgateway-crds.yaml
  - kagent-crds.yaml
  - agentcatalogs.agentregistry.dev.yaml
  - discoveryconfigs.agentregistry.dev.yaml
  - mcpservercatalogs.agentregistry.dev.yaml
  - modelcatalogs.agentregistry.dev.yaml
  - registrydeployments.agentregistry.dev.yaml
  - skillcatalogs.agentregistry.dev.yaml
