replicaCount: 1
image:
  repository: ghcr.io/den-vasyliev/agentregistry-inventory
  pullPolicy: IfNotPresent
  tag: ""

controller:
  leaderElection: false
  logLevel: info
  metricsAddr: ":8081"
  probeAddr: ":8082"

httpApi:
  port: 8080
  mcpPort: 8083
  serviceType: ClusterIP

disableAuth: true

httpRoute:
  enabled: false
  hostname: agentregistry.example.com
  gatewayName: agentgateway-external
  gatewayNamespace: agentgateway-system
  sectionName: http
